### ISSUE TITLE
Cancelling export throws Unhandled Promise Rejection

### ISSUE THREAD

**Issue by Jordyderuijter** [watchyoursixx/HunterSim#47]
When I click on the export button at any moment, the file dialog correctly opens. But when I then cancel the dialog, the follow exception appears in an alert dialog:
![image](https://user-images.githubusercontent.com/3405911/164996574-c044798d-9a9e-49f2-a1e4-6adbb372ad4f.png)

**Comment by klingo** [comment]
For me, this dialog comes immediately when clicking on the "Export" button - never saw a file dialog.

**Comment by watchyoursixx** [comment]
> For me, this dialog comes immediately when clicking on the "Export" button - never saw a file dialog.

Can't seem to reproduce this. Do you still have this issue?

**Comment by klingo** [comment]
> Can't seem to reproduce this. Do you still have this issue?

Yes, seems to be a Firefox-only issue though. Now, nothing happens when clicking on the "Export" button. 

Edit: I opened a new issue #53 regarding exporting under Firefox. Consider my comments here as no longer relevant to the original issue with the unhandled promise.

**Comment by watchyoursixx** [comment]
Marking this issue as fixed. Looking into how to identify browser/make it universal.

Planned to also have copy to clipboard option, so stay tuned for that as well.
