### ISSUE TITLE
Save set without having a loaded set throws Uncaught TypeError

### ISSUE THREAD

**Issue by Jordyderuijter** [watchyoursixx/HunterSim#48]
Whenever you first open the simulator without having a created set loaded yet and then click the "Save set" button, the following error is thrown:

![image](https://user-images.githubusercontent.com/3405911/164996714-f1b9bb18-d667-4fa3-86ca-6236ab65ab1f.png)

**Comment by watchyoursixx** [comment]
Fixed in #56
