### ISSUE TITLE
Race/Spec wrongly displayed after reloading

### ISSUE THREAD

**Issue by klingo** [watchyoursixx/HunterSim#49]
Even though in the settings I selected "Draenei" race and "BM 41/20/0" spec, whenever I reload the page it shows "Orc" and "SV 0/20/41" spec above the active gear.
![image](https://user-images.githubusercontent.com/14639044/164997603-ba02a951-0e3c-4b0d-929c-8a8c9d6c14da.png)

Edit: Just to clarify, the settings are correctly saved/loaded, it is just not reflected on the "main page" upon reloading the page. Also, shouldn't there be a different icon for MM/SV specs?

**Comment by klingo** [comment]
The function '**getRace()**' updates the displayed race. It is however only called when changing the race in the settings. It is **not** called upon loading the page.

Fix: Call the function when loading the page as well.

**Comment by watchyoursixx** [comment]
I added something for saving race, but not talents yet in #56 . The way talents are set up I'll have to create some custom code to extract the points "string".
Also need to add 3 pngs for each spec and add some code to swap that as well.

**Comment by watchyoursixx** [comment]
fixed in #63
