### ISSUE TITLE
Wrong location for "Carapace of Sun and Shadow"

### ISSUE THREAD

**Issue by klingo** [watchyoursixx/HunterSim#57]
"Carapace of Sun and Shadow" is currently configured as _Location:"Sunwell"_, whereas it actually is a LW craftable. Because of that it is not filtered out when unchecking "Crafted" in the item selector.
https://github.com/watchyoursixx/HunterSim/blob/b27454610b4880d21f1197994ad8c4a7882cc187/js/data/gear.js#L1761

**Comment by watchyoursixx** [comment]
closed in #59
