### ISSUE TITLE
Unequipping gems/enchants is not updated in localStorage['gear']

### ISSUE THREAD

**Issue by klingo** [watchyoursixx/HunterSim#58]
Unequipping a gem or enchant, does not trigger an update of the **gear** object in localStorage. It is only getting updated if a an actual gem/enchant is selected.

Thus in order to actually remove a gem/enchant from localStorage (and thus make it relevant for the DPS sim), you need to re-select a gem/enchant in another slot as this triggers a refresh of the whole localStorage['gear'].

**Comment by watchyoursixx** [comment]
fixed in #61
